name: Build x264 with MSVC on Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-x264-msvc:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download x264 source snapshot
      shell: powershell
      run: |
        $version = "20250520-2245"  # 这里改成你需要的快照日期
        $url = "http://download.videolan.org/pub/x264/snapshots/x264-snapshot-$version.tar.bz2"
        Write-Host "Downloading x264 snapshot $version ..."
        Invoke-WebRequest -Uri $url -OutFile "x264-snapshot.tar.bz2"

        Write-Host "Extracting archive..."
        tar -xjf x264-snapshot.tar.bz2
        Rename-Item "x264-snapshot-$version" "x264"

    - name: Build x264 with MSVC
      shell: cmd
      run: |
        REM 查找 VS 安装路径
        for /f "delims=" %%i in ('"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath') do set VS_PATH=%%i

        echo Using VS_PATH=%VS_PATH%
        if not exist "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat" (
          echo ERROR: vcvars64.bat not found!
          exit /b 1
        )

        call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"

        cd x264\build
        nmake -f win32\Makefile.msvc clean
        nmake -f win32\Makefile.msvc

    - name: Collect artifacts and zip
      shell: powershell
      run: |
        $outdir = "$env:GITHUB_WORKSPACE\artifacts"
        if (-Not (Test-Path $outdir)) { New-Item -ItemType Directory -Path $outdir | Out-Null }

        Copy-Item -Path "$env:GITHUB_WORKSPACE\x264\build\include\x264.h" -Destination $outdir
        Copy-Item -Path "$env:GITHUB_WORKSPACE\x264\build\lib\x264.lib" -Destination $outdir
        Copy-Item -Path "$env:GITHUB_WORKSPACE\x264\build\bin\x264.dll" -Destination $outdir

        $zipPath = "$env:GITHUB_WORKSPACE\x264-msvc-win.zip"
        if (Test-Path $zipPath) { Remove-Item $zipPath }
        Compress-Archive -Path "$outdir\*" -DestinationPath $zipPath

    - name: Create git tag v1.0.0
      id: tag
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        if git rev-parse v1.0.0 >/dev/null 2>&1; then
          echo "Tag v1.0.0 already exists"
        else
          git tag -a v1.0.0 -m "Build x264 MSVC v1.0.0"
          git push origin v1.0.0
        fi

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.0
        name: x264 MSVC Windows v1.0.0
        body: x264 build compiled with MSVC on Windows.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.0
        files: x264-msvc-win.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
